defaults:
  - dataset: UKB
  - model: ft_transformer
  - optimizer: adamw
  - training: default

save_path: ./results/DL_based/${model.name}_ep_${training.train_epochs}_bs_${training.batch_size}/${dataset.variable_type}

gpu: 1
test: true

n_fold: 5
n_iterations: 5

wandb: true
project: UKB
